### ISSUE TITLE
Problem import on Netbeans

### ISSUE THREAD

**Issue by mspiropali** [barbeau/EncogME#3]
Hello,

I have a problem importing encog for my project on Netbeans.
Is there any exact way I have to do it?
Because I try adding it to the project's library but it still doesn't recognize it.

Thanks in Advance

**Comment by barbeau** [comment]
Can you share exact error and screenshot?

From working with other Java ME projects, I've had to go back to using NetBeans 6.9.1, IIRC. Newer versions of NetBeans have problems compiling Java ME.

**Comment by mspiropali** [comment]
Sorry for replying late,

I tried many more methods but I still can't  get it working.
I have an assignment on wireless sensor networks for which I need encog.
I run windows xp on a vm with netbeans v8.0.1
By copying the EncogCoreJavaME into the project's folder under src, I can only get org.encog.Encog; and org.encog.EncogError; importing correclty.
Here is a screenshot:
![untitled](https://user-images.githubusercontent.com/26287410/27611595-79e7367e-5b9b-11e7-9a94-286003252e50.png)

**Comment by barbeau** [comment]
For the project folders with "Java ME", in the name, you'll need to import these as Java ME projects in NetBeans, not normal Java projects. 

Where are you trying to run this code? On the WSN nodes or on your desktop machine?

The platform would need to implement Java ME for this project to be usable.

**Comment by mspiropali** [comment]
On my desktop machine, using virtual WSN nodes (Solarium).
I want to use the Encog for my classes, so I just make a Java ME project and copy the encog folder into my project?

**Comment by barbeau** [comment]
No, you need to make sure you have the NetBeans component for Java ME installed (https://netbeans.org/features/java-on-client/java-me.html) . Then, import the projects with Java ME in title in this repo as Java ME projects.

**Comment by barbeau** [comment]
EncogCoreJavaME is the library project you can use with your own Java ME app. EncogJavaMEApp is an example Java ME app that uses the EncogCoreJavaME library.

**Comment by mspiropali** [comment]
Ok i got it, thank you very much!

**Comment by barbeau** [comment]
Great! I'll close the issue then.
